### ISSUE TITLE
Plugin does not work on 1.15.2

### ISSUE THREAD

**Issue by bloggy** [NLthijs48/AreaShop#554]
1.15.2. error in console on startup.

versions:
- Enabling AreaShop v2.6.0#299
- This server is running Tuinity version git-Tuinity-"9616aa9" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
- FastAsyncWorldEdit] Loading FastAsyncWorldEdit v1.15.2
- [WorldEdit] Loading WorldEdit v1.15-204;56c7209

```
[20:19:48] [Server thread/ERROR]: Error occurred while enabling AreaShop v2.6.0#299 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_242]
	at me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:299) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Tuinity-"9616aa9"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	... 12 more

```

**Comment by Syrkulous** [comment]
FAWE Does not work with AreaShop!

You will need to use AWE or normal WE instead
